diff --git a/Makefile b/Makefile
index 9157869..f61ce7e 100644
--- a/Makefile
+++ b/Makefile
@@ -1,8 +1,8 @@
 SCANNER := wayland-scanner
 
-PREFIX=/usr/local
+PREFIX=/usr
 BINDIR=$(PREFIX)/bin
-MANDIR=$(PREFIX)/share/man
+MANDIR=$(PREFIX)/man
 BASHCOMPDIR=$(PREFIX)/share/bash-completion/completions
 
 CFLAGS+=-Wall -Werror -Wextra -Wpedantic -Wno-unused-parameter -Wconversion -Wformat-security -Wformat -Wsign-conversion -Wfloat-conversion -Wunused-result -Wno-strict-prototypes
